---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Check pihole binary exists
      ansible.builtin.stat:
        path: /usr/local/bin/pihole
      register: patch_pihole_bin

    - name: Assert pihole is present
      ansible.builtin.assert:
        that:
          - patch_pihole_bin.stat.exists
        fail_msg: "pihole binary not found"
