---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Check apt cache is fresh
      ansible.builtin.stat:
        path: /var/cache/apt/pkgcache.bin
      register: patch_ubuntu_apt_cache

    - name: Assert apt cache exists
      ansible.builtin.assert:
        that:
          - patch_ubuntu_apt_cache.stat.exists
        fail_msg: "APT cache does not exist after patching"
